
name: Build APK

on:
  push:
    branches:
      - main  # Jab aap main branch me push karenge, workflow run hoga

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Install Cordova
        run: npm install -g cordova@latest

      - name: Create Cordova Project
        run: |
          cordova create myApp
          cd myApp
          cordova platform add android
          cp -r ../* www/
          cordova build android

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: myApp/platforms/android/app/build/outputs/apk/debug/app-debug.apk
